### ISSUE TITLE
Issue with DateTime Formatting

### ISSUE THREAD

**Issue by nidhim** [carlopantaleo/tableexport-xls-bold-headers#1]
Hello,
  I have the following setting in my code :
        type: 'excel' , filename : excelName, ignoreColumn :[0] , escape : 'false'

All DateTime columns are getting truncated 
e.g.
2016-07-11 03:51:14.000000 PM is truncated to  51:14.0

Any advice ?

Thanks,
NM

**Comment by carlopantaleo** [comment]
Hello,
Could you please provide a working example of your issue? I'm not able to reproduce it, I don't get truncated DateTime columns...

Thanks

**Comment by carlopantaleo** [comment]
Hello,
even after further investigation, I can't reproduce the issue.
If you have a working example of the problem, please reopen the issue.

Thanks.
